site_name: SoftwareTemplate-Simplified
docs_dir: source
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
        python:
          paths: [../src]
          options:
            show_signature_annotations: true
            docstring_style: google
            signature_crossrefs: true
            modernize_annotations: true
            show_source: false
            members_order: 'source'
            show_if_no_docstring: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            merge_init_into_class: true
            heading_level: 3
            parameter_headings: true
            show_root_heading: true
      

          import:
          - url: https://docs.python-requests.org/en/master/objects.inv
- search


theme:
  name: material

nav:
  - Home: index.md
  - Code docummentation:
    - Train: autodoc/train.md 
  