name: docs

on:
  workflow_dispatch:
  # uncomment to make it runnable after each push into master
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install "mkdocs>=1.6.0" "mkdocs-material>=9.5.0" "mkdocstrings-python>=1.10.0"

      - run: cd docs; mkdocs gh-deploy --force
      

